spring:
  application:
    name: bizscraper
  datasource:
    url: jdbc:postgresql://localhost:5432/bizscraper
    username: postgres
    password: zxca
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        entityManagerFactoryInterface: jakarta.persistence.EntityManagerFactory


google:
  api:
    key: ${GOOGLE_PLACES_API_KEY}