spring:
  application:
    name: bizscraper
  datasource:
    url: jdbc:postgresql://localhost:5432/bizscraper
    username: postgres
    password: zxca
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        entityManagerFactoryInterface: jakarta.persistence.EntityManagerFactory


google:
  api:
    key: ${GOOGLE_PLACES_API_KEY}

zoho:
  api:
    refresh-token: ${ZOHO_REFRESH_TOKEN}
    client-id: "1000.SXTTSP1TEF41IA9WKLTL8EVX7LR1AZ"
    client-secret: ${ZOHO_CLIENT_SECRET}