spring:
  application:
    name: bizscraper
  datasource:
    url: jdbc:postgresql://localhost:5432/bizscraper
    username: postgres
    password: zxca


google:
  api:
    key: ${GOOGLE_PLACES_API_KEY}